config/routes.rb
Rails.application.routes.draw do


  #get 'users/my_portfolio'
  devise_for :users
  root 'welcome#index'

  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'

  resources :user_stocks, only: [:create, :destroy]

  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'

  resources :friendships, only: [:create, :destroy]

  resources :users, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/friends/_list.html.erb
<!--friends table-->
<%# only displays the table if @friends from users_controller is not empty %>
<% if !@friends.empty? %>

  <div class="row mt-3">

    <div class="col-sm-9">

      <table class="table table-bordered table-hover">
        <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Actions</th>
        </tr>
        </thead>

        <tbody>
        <%# @friends will pass the results from user.friends
              and the instance variable comes from the users_controller%>
        <% @friends.each do |friend| %>

          <tr>
            <th scope="row"><%= friend.email %></th>
            <td><%= friend.first_name %></td>
            <td><%= friend.last_name %></td>


            <td>
              <%# the link below will post to users_controller#show %>
              <%= link_to 'View Profile', user_path(friend), class: 'btn btn-sm btn-outline-success' %>

              <%# this link_to will call the action Destroy from the friendships_controller.
                  Since it will be passing the friend ID, I'll have to grab the user id and look for the friendship
                  between the user and the friend to delete it
                  %>
              <%= link_to 'Stop Following', friendship_path(friend), method: :delete, class: 'btn btn-sm btn-warning ml-2' %>
            </td>
          </tr>


        <% end %>

        </tbody>
      </table>

    </div>

  </div>
  <!--end friends table-->
<% end %>