config/routes.rb
Rails.application.routes.draw do


  #get 'users/my_portfolio'
  devise_for :users
  root 'welcome#index'

  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'

  resources :user_stocks, only: [:create, :destroy]

  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'

  resources :friendships, only: [:create, :destroy]

  resources :users, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/stock.rb
class Stock < ApplicationRecord

  # the lines below create the many to many association.
  # It's importante to include "through" as it allows for functionalities like
  # stock.users and also user.stocks
  has_many :user_stocks
  has_many :users, through: :user_stocks

  # capitalize the ticker before saving it into the database
  before_save {self.ticker = ticker.upcase}

  # validations
  validates :name, :ticker, presence: true


  # this is a class method (I had to use self. to make it
  # available even without an instance of this model)
  def self.new_lookup(ticker_symbol)


    # this is what connects us to the API
    # The value for publish token is an API key that we hid inside the credentials.yml.enc
    # This file is encypted and the only way of acessing it is by using the master.key
    client = IEX::Api::Client.new(
        publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
        endpoint: 'https://sandbox.iexapis.com/v1')

    # the method .price is from the API documentation and since ruby doesn't need RETURN,
    # this will return the stock price based on the ticker_symbol given
    #
    # client.price(ticker_symbol) -- this has been commented out because we will now
    # return an object with more information intead of just the price
    #

    # here I'm basically creating a new object of type Stock with the following attributes:
    # ticker - I'll pass whatever this method received through the ticker_symbol
    # name - this is from the gem documentation:- client.company(ticker_symbol).company_name
    # price - also from the documentation:- client.price(ticker_symbol)
    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name,
          last_price: client.price(ticker_symbol)
      )

    rescue => exception # this is to handle exceptions in case the user enters an invalid symbol.

      return nil
      # in case of an exception, we just return nil and then we check that in the stocks_controller#search

    end # end exception handling

  end # end new_loockup method


  def self.check_db(ticker_symbol)
    # this method will check if a given ticker_symbol is already in the database. This mwthod is called from
    # the user_stocks_controller#create method.
    ticker_symbol.upcase!
    where(ticker: ticker_symbol).first

  end # end check_db


end # end stock

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search

    # first I check if the user actually entered a stock symbo
    if params[:stock].present?

      # this will run the method new_lookup from the Stock model
      # and save the value into the variable @stock
      @stock = Stock.new_lookup(params[:stock])

      # if the API call DOESN'T return nil, then it means that the user entered
      # a valid symbol. For that case, we render the view with the stock information,
      # otherwise, we display an alert and redirect to my_portfolio
      if @stock

        ### the line below got deprecated by the new JS response
        ### render 'users/my_portfolio'


        # respond_to will handle the response to the Ajax request that comes from the form in
        # my_portfolio.html.erb.
        respond_to do |format|
          format.js {render partial: 'users/result'} # This will expect a JS file (_result.JS.erb)
        end

      else

        ### the lines below got deprecated by the new JS response
        ### flash[:alert] = "#{params[:stock]} is not a valid stock symbol!"
        ### redirect_to my_portfolio_path

        respond_to do |format|
          # I've changed from flash to flash.now so it disappears when I hit search again
          flash.now[:alert] = "#{params[:stock]} is not a valid stock symbol!"
          format.js {render partial: 'users/result'} # This will expect a JS file (_result.JS.erb)
        end

      end # end if @stock

    else

      ### the lines below got deprecated by the new JS response
      ### flash[:alert] = "Please enter a Symbol to Search"
      ### redirect_to my_portfolio_path

      respond_to do |format|
        # I've changed from flash to flash.now so it disappears when I hit search again
        flash.now[:alert] = "#{params[:stock]} Please enter a Symbol to Search!"
        format.js {render partial: 'users/result'} # This will expect a JS file (_result.JS.erb)
      end

    end # end if params[:stock].present?

  end # end search

end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_list.html.erb
<!--stocks table-->
<%# only displays the table if @tracked_stocks from users_controller is not empty %>
<% if !@tracked_stocks.empty? %>

  <div class="row mt-3">

    <div class="col-sm-9">

      <table class="table table-bordered table-hover">
        <thead>
        <tr>
          <th scope="col">Symbol</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
        </thead>

        <tbody>
        <%# @tracked_stocks will pass the results from user.stocks
              and the instance variable comes from the users_controller%>
        <% @tracked_stocks.each do |stock| %>

          <tr>
            <th scope="row"><%= stock.ticker %></th>
            <td><%= stock.name %></td>
            <td><%= stock.last_price %></td>
            <td>

              <%# this will add a button that will post to the create action from the user_stocks_controller.
                  It's passing the current_user (helper method from the gem DEVISE) and the ticker that the user
                  searched for. The method create will have to check if the ticker already exists in the stocks table
                  and if not, it will have to do an API request to get the information
              %>

              <%# ADDED LATER: The button will only show if the can_track_stocks returns true.
                  This method is located in the Users model%>
              <% if current_user.can_track_stock?(stock.ticker) %>

                <%= link_to "Add to portfolio", user_stocks_path(user: current_user, ticker: stock.ticker),
                            class: "btn btn-sm btn-success ml-2", method: :post%>

              <% elsif current_user.id != @user.id %>

                <%# if the buttons doesn't show up and the current_user id is different from the user page, then it displays a badge:
                    * You are already tracking 10 stocks if the user has 10 stocks
                    * You are already tracking this stock if there's already an association between the user and the stock
                    Both methods are located on the User model
                %>
                <span class="badge badge-secondary ml-2">

                  You are already tracking

                  <% if !current_user.under_stock_limit? %>

                    10 stocks

                  <% end %>

                  <% if current_user.stock_already_tracked?(stock.ticker) %>

                    this stock

                  <% end %>

                </span>

              <% end %> <%# end if current_user.can_track_stock?(@stock.ticker) %>


              <%# this Remove button will pass in the stock ID. But since we want to delete the association, I will have
                  to handle this in the user_stocks_controller
                  ADDED LATER: it will only show the remove button if the @user.id is the same as the user logged in. %>

              <% if current_user.id == @user.id %>

                <%= link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-warning' %>


              <% end %> <%# if current_user.id == @user.id %>

            </td>

          </tr>

        <% end %> <%# end @tracked_stocks.each do %>

        </tbody>
      </table>

    </div>

  </div>
  <!--end stocks table-->
<% end %>