config/routes.rb
Rails.application.routes.draw do


  #get 'users/my_portfolio'
  devise_for :users
  root 'welcome#index'

  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'

  resources :user_stocks, only: [:create, :destroy]

  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'

  resources :friendships, only: [:create, :destroy]

  resources :users, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  # the lines below create the many to many association.
  # It's important to include "through" as it allows for functionalities like
  # stock.users and also user.stocks
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships


  def under_stock_limit?
    # the method simply executes user.stocks.count and returns
    # true or false if the counter is greater than 9

    stocks.count < 10

  end # end under_stock_limit?


  def stock_already_tracked?(ticker_symbol)
    #this method will check if the stock is already been tracked.

    # if the stock is not even on the database, just return false
    # the method check_db comes from the Stock model
    stock = Stock.check_db(ticker_symbol)
    return false unless stock

    # if the stock is in fact in the DB, I have to check if the user is already tracking it
    # for example, user.stocks.where(id: 13).exists?
    # This will test if there's an association between the logged user and the stock id passed through
    stocks.where(id: stock.id).exists?
  end


  def can_track_stock?(ticker_symbol)
    # the method will evaluate if the user can track or not the stock based on the two methods above the verify if
    # the user is tracking less than 10 stocks and if he/she is not already tracking that stock

    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end


  def full_name
    # this method returns the first_name and last_name from the model to the navbar.
    first_name || last_name ? "#{first_name} #{last_name}" : "Anonymous"
  end



  def self.matches(field_name, param)
    # this method will be used to search on a field_name(first name, last name, email) for a specific query(param)
    # It will be used by the methods below to search each field_name individually
    where("#{field_name} like ?", "%#{param}%")
  end


  def self.search(param)
    # this method will execute the search of a term through multiple "options" (first name, last name and email)
    # first it strips out any spaces from the param and the it runs the three methods below:
    # first_name_matches, last_name_matches and email_matches. Then, it filters only for unique results and
    # saves the value to the variable to_send_back. If nothing returns, then the method returns nil, otherwise, it returns
    # the value that was stored.
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    to_send_back.nil? ? nil : to_send_back
    #return  nil unless to_send_back
    #to_send_back
  end

  def self.first_name_matches(param)
    # please refer to method above to understand the logic
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    # please refer to method above to understand the logic
    matches('last_name', param)
  end

  def self.email_matches(param)
    # please refer to method above to understand the logic
    matches('email', param)
  end

  def except_current_user(friends)
    # this method removes the current user from the friends Result Set and it's called from the users_controller.
    # It will loop through the friends list and compare the id with the id of the current_user (method from DEVISE)
    # if the ID is the same, then it removes it from the ResultSet

    friends.reject { |friend| friend.id == self.id }
  end

  def not_friends_with?(id_of_friend)
    # this method will run a query to see if the relationship friendship exists between the user and the id of the friend.
    # This methos is called from the _friend_result_html.erb
    # Here is how the query breakdown looks like
    #   * list all friends for the user - user.friends
    #   * look if one of the friends has the ID that was passed in check if it exists
    #   * if the friend is found, it returns true
    #   * then I inverted the result to make it more readible so if the query returns true, the it means that they are friends
    #
    !self.friends.where(id: id_of_friend).exists?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def my_portfolio

    # devise provies a helper method called current_user, that returns the current user logged in
    # by calling .strocks from a user, we get a list of stocks that are associated to that user
    @tracked_stocks = current_user.stocks
    @user = current_user

  end # end my_portfolio

  def my_friends
    # this method simply gets all friends from the logged user and passes it through to my_friends.html.erb view
    # the method current_user is from DEVISE and brings back the current user

    @friends = current_user.friends

  end # end my_frieds

  def search
    # this is the methods that wil handle the search functionality from my_friends.html.erb
    # The steps are:
    #   * Check if the user actually entered something in the search field, if not, display a flash notice
    #   * then user the method search from the User model to retrieve the results that match the params
    #   * after that I removed the current user from the result through the except_current_user from the User model
    #   * if the friend exists, then display it, if not, inform user not found

    if params[:friend].present?

      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)

      if @friends

        respond_to do |format|
          format.js { render partial: 'users/friend_result'}
        end

      else

        respond_to do |format|
          flash.now[:alert] = "Couldn't find user"
          format.js { render partial: 'users/friend_result'}
        end

      end # end @friend

    else

      respond_to do |format|
        flash.now[:alert] = "Please enter a friend name or email to search"
        format.js { render partial: 'users/friend_result'}
      end

    end # end params[:friend].present?


  end # end search

  def show

    @user = User.find(params[:id])

    # tracked_stocks is an instance variable that will be users in the users/show.html.erb
    @tracked_stocks = @user.stocks

  end


end # end class

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friend_result.html.erb
<%# this partil is loaded from my_friends.html.erb %>

<%# this will render the partial layouts/_messages.html.erb that display messages
    when an invalid/blank user symbol is entered %>
<%= render 'layouts/messages' %>

<%# if the instance variable @friends from users_controller is not passed, display the info %>
<% if @friends %>

  <div class="card card-header mt-3 results-block">

    <table class="col-md-12 mb">

      <tbody>

        <% @friends.each do |friend| %>

          <tr class="table-row-space">

            <td><strong>Name: </strong> <%= friend.full_name %></td>
            <td class="pl-2"><strong>Email: </strong> <%= friend.email %></td>

            <%# the link below will post to users_controller#show %>
            <td class="pl-2"><strong>Actions: </strong><%= link_to "View Profile", user_path(friend), class: "btn btn-sm btn-outline-success ml-1" %>

              <%# The block below will only display the Follow button only if the method not_friends_with? from the User model returns true
              %>
              <% if current_user.not_friends_with?(friend.id) %>

                <%# this will post to the friendships_controller, into the create action %>
                <%= link_to "Follow", friendships_path(friend: friend), class: "btn btn-sm btn-success ml-2", method: :post%>

                  <% else %>

                    <span class="badge badge-secondary ml-2">
                      You are friends
                    </span>

                  <% end %>

              </td>

          </tr>

      <% end %> <%# end @friends.each %>

      </tbody>

    </table>


  </div>

<% end %>

app/views/users/_friend_result.js.erb
/*  this document is called from the controller users_controller because of the respond_to
    and what the line below does is select the DIV with ID results in the my_friends.html.erb
    and render the content of _friend_results.html.erb in it.
    To run JavaScript code within embedded ruby code, we need a method called escape_javascript().
    Alternatively, I could have used <%#= j render 'users/result.html'  %>
 */
document.querySelector('#results').innerHTML = '<%= escape_javascript(render 'users/friend_result.html') %>'

app/views/users/_result.html.erb
<%# this will render the partial layouts/_messages.html.erb that display messages
    when an invalid/blank stock symbol is entered %>
<%= render 'layouts/messages' %>

<%# if a stock from stocks_controller is passed, display the info %>
<% if @stock %>
  <div class="card card-header mt-3 results-block">

    <strong>Symbol: </strong> <%= @stock.ticker.upcase %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>

    <%# this will add a button that will post to the create action from the user_stocks_controller.
        It's passing the current_user (helper method from the gem DEVISE) and the ticker that the user
        searched for. The method create will have to check if the ticker already exists in the stocks table
        and if not, it will have to do an API request to get the information
    %>

    <%# ADDED LATER: The button will only show if the can_track_stocks returns true.
        This method is located in the Users model%>
    <% if current_user.can_track_stock?(@stock.ticker) %>

      <%= link_to "Add to portfolio", user_stocks_path(user: current_user, ticker: @stock.ticker),
                                    class: "btn btn-sm btn-success ml-2", method: :post%>

    <% else %>

      <%# if the buttons doesn't show up, then it displays a badge:
          * You are already tracking 10 stocks if the user has 10 stocks
          * You are already tracking this stock if there's already an association between the user and the stock
          Both methods are located on the User model
      %>
      <span class="badge badge-secondary ml-2">
        You are already tracking

        <% if !current_user.under_stock_limit? %>
          10 stocks
        <% end %>

        <% if current_user.stock_already_tracked?(@stock.ticker) %>
          this stock
        <% end %>
      </span>

    <% end %> <%# end if current_user.can_track_stock?(@stock.ticker) %>

  </div>

<% end %>

app/views/users/_result.js.erb
/*  this document is called from the controller stocks_controller because of the respond_to
    and what the line below does is select the DIV with ID results in the my_portfolio.html.erb
    and render the content of _results.html.erb in it.
    To run JavaScript code within embedded ruby code, we need a method called escape_javascript().
    Alternatively, I could have used <%#= j render 'users/result.html'  %>
 */
document.querySelector('#results').innerHTML = '<%= escape_javascript(render 'users/result.html') %>'

app/views/users/my_friends.html.erb
<h1>Friends</h1>


<div class="search-area">

  <h3>Search Friends</h3>

  <%# since there is NO model that we gonna use in this page,
      we will user form_tag instead of form_for.
      I need to pass where the form submits the information to, and the method
      In this case, it's submitting to search_friend_path (which is users#search)
      To enable Ajax, I had to add remote: true, which in HTML translates to data-remote="true" %>

  <%= form_tag search_friend_path, remote: true, method: :get do %>

    <div class="form-row">

      <!--Input field-->
      <div class="col-sm-9">

        <%# the text_field_tag requires a name for the text field - :stock
            it also requires what will be passed through the params - params[:stock]
            Se I'm basically passing whatever is put into the text field will be the value
            of my parameter stock.
            The url will be something like: localhost/my_portfolio?stock="AAPL" %>
        <%= text_field_tag :friend, params[:friend], placeholder: "Name or email",
                           autofocus: true, class: "form-control form-control-lg text-uppercase" %>

      </div> <!-- end input field-->


      <!--Button search stock-->
      <div class="col-sm-3">

        <%# the button tag will create a button and it requires a type %>
        <%= button_tag type: :submit, class: "btn btn-lg btn-success" do %>
          <%= fa_icon 'search' %>
        <% end %>

      </div> <!--end button search stock-->


    </div>

  <% end %> <%# end form_tag %>
</div>

<%# this bit will handle the Ajax request and response to display the results
    from the the API request.
    Since the form has the flag remote:true, this means the result will be handle by Ajax.
    The form posts the information to the stocks_controller and calls for the method search.
    The method search then hits the API and sends the response as JS to Ajax, that renders _result.JS.erb, which
    then renders _result.html.erb
%>
<div id="results">
</div>



<%# if the friends instance variable from the users_controller is not empty,
then render the partial friends/_list.html.erb%>
<% if !@friends.empty? %>

  <%= render 'friends/list' %>

<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>


<div class="search-area">

  <h3>Search Stocks</h3>

  <%# since there is NO model that we gonna use in this page,
      we will user form_tag instead of form_for.
      I need to pass where the form submits the information to, and the method
      In this case, it's submitting to search_stock_path (which is stocks#search)
      To enable Ajax, I had to add remote: true, which in HTML translates to data-remote="true" %>

  <%= form_tag search_stock_path, remote: true, method: :get do %>

    <div class="form-row">

      <!--Input field-->
      <div class="col-sm-9">

        <%# the text_field_tag requires a name for the text field - :stock
            it also requires what will be passed through the params - params[:stock]
            Se I'm basically passing whatever is put into the text field will be the value
            of my parameter stock.
            The url will be something like: localhost/my_portfolio?stock="AAPL" %>
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock symbol",
                           autofocus: true, class: "form-control form-control-lg text-uppercase" %>

      </div> <!-- end input field-->


      <!--Button search stock-->
      <div class="col-sm-3">

        <%# the button tag will create a button and it requires a type %>
        <%= button_tag type: :submit, class: "btn btn-lg btn-success", data: {disable_with: "#{fa_icon('spinner', class: 'fa-spin')}" } do %>
          <%= fa_icon 'search' %>
        <% end %>

      </div> <!--end button search stock-->


    </div>

  <% end %> <%# end form_tag %>
</div>

<%# this bit will handle the Ajax request and response to display the results
    from the the API request.
    Since the form has the flag remote:true, this means the result will be handle by Ajax.
    The form posts the information to the stocks_controller and calls for the method search.
    The method search then hits the API and sends the response as JS to Ajax, that renders _result.JS.erb, which
    then renders _result.html.erb
%>
<div id="results">
</div>

<%= render 'stocks/list' %>

app/views/users/show.html.erb
<h2>User Details</h2>

<div class="card card-header mt-3 results-block">

  <table class="col-md-12 mb">

    <tbody>

      <tr class="table-row-space">

        <td><strong>Name: </strong> <%= @user.full_name %></td>
        <td class="pl-2"><strong>Email: </strong> <%= @user.email %></td>
        <td class="pl-2">

          <%# The block below will only display the Follow button only if the method not_friends_with? from the User model returns true
          %>
          <% if current_user.not_friends_with?(@user.id) %>

            <%# this will post to the friendships_controller, into the create action %>
            <%= link_to "Follow", friendships_path(friend: @user), class: "btn btn-sm btn-success ml-2", method: :post%>

          <% else %>

                  <span class="badge badge-secondary ml-2">
                    You are friends
                  </span>

          <% end %>

        </td>

      </tr>

    </tbody>

  </table>

</div>

<%# this piece of code is getting the @tracked_socks from users_controller#show and checking if it is empty.
    If it's not empty, then it will render the stocks list for that particular user.
%>
<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% else %>
  <p class="lead">This user is not tracking any stocks</p>
<% end %>