config/routes.rb
Rails.application.routes.draw do


  #get 'users/my_portfolio'
  devise_for :users
  root 'welcome#index'

  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'

  resources :user_stocks, only: [:create, :destroy]

  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'

  resources :friendships, only: [:create, :destroy]

  resources :users, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.erb
<% if notice %>

  <div class="alert alert-success alert-dismissible fade show mt-3 col-sm-9" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>


<% end %>


<% if alert %>

  <div class="alert alert-danger alert-dismissible fade show mt-3 col-sm-9" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <div class="container">

    <%= link_to "Finance Tracker", root_path, class: "navbar-brand"%>

    <%# will only display the options if there's a user logged in.
        the method current_user is a helper from the DEVISE gem and returns the current
        user logged in %>
    <% if current_user %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= "active" if request.path == my_portfolio_path %>">
            <%= link_to "My Portfolio", my_portfolio_path, class: "nav-link" %>

          </li>
          <li class="nav-item">
            <%= link_to "My Friends", my_friends_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">

              <%# the link comes from DEVISE, and this also shows a different way of creating a link BLOCK %>
              <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                Edit Profile <%= fa_icon "edit", class: "ml-3" %>
              <% end %>

              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>

          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>


        <!-- right-hand side menu -->
        <ul class="navbar-nav ml-auto">

          <!-- Welcome, #name -->
          <li class="nav-item mt-2 mr-3">
            <%# this will call a method from the User mode:
                * current_user is from DEVISE and already returns the current user
                * full_name is located on the User model and concatenates the first and last name from the user %>
            <%= fa_icon 'user', class: "mr-1" %> <%= current_user.full_name %>
          </li>
          <!-- end Welcome, #name -->

          <!-- logout -->
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger mr-3"%>
          </li><!-- end logout -->

        </ul> <!-- end right-hand side menu -->


        <!--search-->
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <!-- end search -->

      </div>




    <% end %>



  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%# renders the partial navigation.html.erb %>
    <%= render 'layouts/navigation' %>

    <div class="container">

      <%### the block below got deprecated as we are running the messages from the users/_result.html.erb
            This change happened because we implemented Ajax and used a data-remote form on my_portfolio.html.erb  %>
      <%### renders the partial _messages.html.erb %>
      <%= render 'layouts/messages' %>

      <%= yield %>

    </div>

  </body>
</html>